### PR TITLE
[BUGFIX] Don't throw exceptions until after checking anyOf / oneOf

### LINKED ISSUE #393: Oneof/AnyOf/AllOf applied to the properties of an object
I have tried these schemas based on these answers:

* http://stackoverflow.com/questions/31839578/how-to-define-a-json-schema-that-requires-at-least-one-of-many-properties
* http://stackoverflow.com/questions/25014650/json-schema-example-for-oneof-objects

But I can't get them to work:

```php
<?php

use JsonSchema\Validator;
use JsonSchema\Constraints\Constraint;
use JsonSchema\Exception\ValidationException;

$validator = new Validator;

$data = file_get_contents('./test.json');

$data = json_decode($data, true);

$validator->validate(
    $data,
    json_decode(json_encode([
        'type' => 'object',
        'properties' => [
            'response' => [
                'type' => 'object',
                'oneOf' => [
                    ['required' => ['error']],
                    ['required' => ['result']]
                ],
                'properties' => [
                    'error' => [
                        'type' => 'object'
                    ],
                    'result' => [
                        'type' => 'object'
                    ]
                ]
            ]
        ],
        'required' => ['response']
    ])),
    Constraint::CHECK_MODE_TYPE_CAST | Constraint::CHECK_MODE_EXCEPTIONS
);

var_dump($validator->isValid());
// JsonSchema\Exception\ValidationException with message 'Error validating /response/error: The property error is required'
```

```php
<?php

use JsonSchema\Validator;
use JsonSchema\Constraints\Constraint;
use JsonSchema\Exception\ValidationException;

$validator = new Validator;

$data = file_get_contents('./test.json');

$data = json_decode($data, true);

$validator->validate(
    $data,
    json_decode(json_encode([
        'type' => 'object',
        'properties' => [
            'response' => [
                'type' => 'object',
                'oneOf' => [
                    [
                        'properties' => [
                            'error' => [
                                'type' => 'object'
                            ],
                        ]
                    ],
                    [
                        'properties' => [
                            'result' => [
                                'type' => 'object'
                            ],
                        ],
                    ]
                ]
            ]
        ],
        'required' => ['response']
    ])),
    Constraint::CHECK_MODE_TYPE_CAST | Constraint::CHECK_MODE_EXCEPTIONS
);

var_dump($validator->isValid());
// JsonSchema\Exception\ValidationException with message 'Error validating /response: Failed to match exactly one schema'
```

The data is like:

```
{
    "response": {
        "result": {}
    }
}
```

```
{
    "response": {
        "error": {}
    }
}
```

### PR DESCRIPTION
**Pull request by erayd**
## What
Don't throw exceptions until evaluation of `anyOf` / `oneOf` has completed.

## Why
This is a bug. Fixes #393.

### CODE REVIEW

**Comment by shmax** [comment]
Nice one LGTM

**Comment by erayd** [comment]
Thanks :-).

Having thought about this a little more, I might refactor this to take advantage of bubbled exceptions, rather than just turning them off during anyOf / oneOf - that would be better from a performance perspective.

**Comment by erayd** [comment]
I should also add tests that cover this case.

**Comment by erayd** [comment]
@shmax How's that?

**Comment by shmax** [comment]
It's a thing of beauty. LGTM

**Comment by erayd** [comment]
Thanks :-)

**Comment by erayd** [comment]
Grr. Apparently I committed the pre-style-fix version. Travelling now, will commit the correct version once I'm home.

**Comment by erayd** [comment]
There we go - much better :-).

File: tests/Constraints/OfPropertiesTest.php [hunk 1]
```diff
@@ -223,4 +226,44 @@ public function getInvalidTests()
...
+            }
+        }');
+        $data = json_decode('{"propertyOne":"ABC"}');
+
+        $v = new Validator();
+        $v->validate($data, $schema, Constraint::CHECK_MODE_EXCEPTIONS);
+        $this->assertTrue($v->isValid());
+    }
+
+    public function testNoPrematureOneOfException()
```
Comment (bighappyface) [inline tests/Constraints/OfPropertiesTest.php]: Am I seeing things or is this method identical to `testNoPrematureAnyOfException`?

Comment (erayd) [inline tests/Constraints/OfPropertiesTest.php]: You're not seeing things - thanks for spotting that one! Will sort once I'm back at my desk later today.

Comment (erayd) [inline tests/Constraints/OfPropertiesTest.php]: @bighappyface Fixed.
