### PR TITLE
Fixes min/max properties validation for non objects

### LINKED ISSUE #260: Checking maxProperties when payload is not an object generates PHP Warning
- package version used: `2.0.1` (9ef71fdf8aa59a93977446468fc718ea01115a83)
- schema
```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "foo": {
      "type": "object",
      "maxProperties": 1,
      "additionalProperties": false,
      "patternProperties": {
        "^[a-zA-Z]+$": {
          "type": "boolean"
        }
      }
    }
  }
}
```
- input:
```
{
  "foo": 123
}
```

It generates:
```
PHP Warning:  get_object_vars() expects parameter 1 to be object, integer given in /tmp/repro/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/ObjectConstraint.php on line 169
```

I think it shouldn't attempt to do anything with `ObjectConstraint` when the payload is not an object.

For comparison, version `1.6.1` (cc84765fb7317f6b07bd8ac78364747f95b86341) produces no warning (and validates properly).

### PR DESCRIPTION
**Pull request by schrobak**
I've added a few tests that covers the problem described in #260.

Also I went the way that previous implementation was done with single `if (is_object($property))`.
Please have a look at https://github.com/bighappyface/json-schema/blob/1.6.1/src/JsonSchema/Constraints/UndefinedConstraint.php#L169-L186 for reference.

Fixes #260

/cc @mirfilip @bighappyface

### CODE REVIEW

**Comment by bighappyface** [comment]
+1

@mirfilip ?

File: tests/JsonSchema/Tests/Constraints/MinMaxPropertiesTest.php [hunk 1]
```diff
@@ -0,0 +1,108 @@
...
+                  "value": 1
+                }',
+                '{
+                  "type": "object",
+                  "properties": {
+                    "value": {"type": "object", "minProperties": 1}
+                  }
+                }'
+            ),
+            array(
```
Comment (jojo1981) [inline tests/JsonSchema/Tests/Constraints/MinMaxPropertiesTest.php]: Duplicate test data set here?

**Comment by mirfilip** [comment]
I needed some time to get familiar with #215 and all the PRs that were tried there. So, this fixes both #260 and original #215. Verified.

@bighappyface go ahead with merge. We should probably release 2.0.1 even with just that fix onboard. Anyway, there are some things about `ObjectConstraint` that still look sketchy to me.

**Comment by jojo1981** [comment]
+1 Go ahead.

**Comment by schrobak** [comment]
@bighappyface any ETA on releasing this?
